dist: bionic
language: java

addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-stable/xUbuntu_18.04/ /'
        key_url: 'https://download.opensuse.org/repositories/network:messaging:zeromq:release-stable/xUbuntu_18.04/Release.key'
    packages:
      - build-essential
      - make
      - pkg-config
      - automake
      - autoconf-archive
      - libtool
# https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Arelease-stable&package=libzmq3-dev
      - libzmq3-dev

matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk9
    - jdk: oraclejdk11
    - jdk: openjdk9
    - jdk: openjdk11

install:
  - echo 'https://github.com/travis-ci/travis-ci/issues/8667'

script: ./gradlew test
after_script: ./gradlew --no-daemon publishToMavenLocal
